### ISSUE TITLE
Fix local storage

### ISSUE THREAD

**Issue by JXG052** [JXG052/Travel-App#18]
code lines 5-32 and code lines 105-113.

**Comment by seacrest3** [comment]
I found 1 issue that's when the local storage is empty and one is trying to get item from local storage.  he would get "Uncaught TypeError: Cannot read properties of null (reading 'push')".

**Comment by seacrest3** [comment]
"Uncaught TypeError" has been fixed by checking if getting items from local storage would return "null".
